### ISSUE TITLE
error in protobuf creation

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#2]
Traceback (most recent call last):
  File "C:\Users\rangabar.KEYSIGHT\Desktop\snappi_env\openapiart\lib\site-packages\openapiart\openapiart.py", line 102, in _generate
    protobuf.generate(self._openapi)
  File "C:\Users\rangabar.KEYSIGHT\Desktop\snappi_env\openapiart\lib\site-packages\openapiart\openapiartprotobuf.py", line 24, in generate
    self._write_request_msg(path_object)
  File "C:\Users\rangabar.KEYSIGHT\Desktop\snappi_env\openapiart\lib\site-packages\openapiart\openapiartprotobuf.py", line 44, in _write_request_msg
    operation = self._get_operation(path_item_object)
  File "C:\Users\rangabar.KEYSIGHT\Desktop\snappi_env\openapiart\lib\site-packages\openapiart\openapiartprotobuf.py", line 30, in _get_operation
    operation_id = path_item_object['operationId']
TypeError: string indices must be integers
Bypassed creation of protobuf file: string indices must be integers

**Comment by ajbalogh** [comment]
Please retry your test case with the latest version of openapiart 0.0.26.

**Comment by ajbalogh** [comment]
@Rangababu-R have you retried your test case with the latest version of openapiart and is it resolved?

**Comment by Rangababu-R** [comment]
@ajbalogh could not get back, will update you tomorrow IST first half.

**Comment by Rangababu-R** [comment]
@ajbalogh issue is still seen in the latest branch too.
