### ISSUE TITLE
route should created according to the valid HTTP methods

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/openapiart#252]
**Version information**
This is within branch https://github.com/open-traffic-generator/openapiart/tree/servergen/openapiart

**Describe the bug**
Getting this error when execute this PR to generate snappi
```
Traceback (most recent call last):
  File "D:\OTG\Codebase\snappi\setup.py", line 30, in <module>
    openapiart.OpenApiArt(
  File "D:\OTG\Codebase\VenvPython39\lib\site-packages\openapiart\openapiart.py", line 221, in GenerateGoServer
    servergen.generate()
  File "D:\OTG\Codebase\VenvPython39\lib\site-packages\openapiart\goserver\goserver.py", line 38, in generate
    self._loadyaml()
  File "D:\OTG\Codebase\VenvPython39\lib\site-packages\openapiart\goserver\goserver.py", line 56, in _loadyaml
    self._loadroute(url, pathobj)
  File "D:\OTG\Codebase\VenvPython39\lib\site-packages\openapiart\goserver\goserver.py", line 75, in _loadroute
    raise AttributeError(f"controller name missing from '{url} - {methodname}:'\nUse tags: [<name>]")
AttributeError: controller name missing from '/results/metrics - description:'
Use tags: [<name>]
```

**To Reproduce**
This is happening because it is expecting "description" should contain "tags"
```
  /results/metrics:
    description: |-
      Metrics API
    post:
      tags:
      - Metrics
```

**Expected behavior**
snappi should generate without any error

**Additional context**
Nil

**Comment by alakendu** [comment]
@jkristia Could you please comment on methodobj restriction

**Comment by jkristia** [comment]
Currently all methods on a given route must be on the same controller, and therefore the Tag (which is the controller name) must be at the route level, not method level.

**Comment by jkristia** [comment]
yes this is a problem in the current implementation. It is expected to only contain valid http methods on the route. This will need to be fixed

**Comment by alakendu** [comment]
This should available in https://github.com/open-traffic-generator/openapiart/releases/tag/v0.1.33
